### PR TITLE
Resolve #36 with a float: right of a.slide

### LINKED ISSUE #36: Titles of slider nav menu render under the slide (forward) image
For example - see Displays And Merchandising below

navmenuunderslide

### PR DESCRIPTION
**Pull request by djowett**
Fixed menu looks like this
navmenuunderslidefixed
Fixes #36

### CODE REVIEW

**Comment by bierik** [comment]
I can not reproduce that issue. The ``` margin-right ``` prevents the text from rendering under the arrow.

bildschirmfoto 2015-08-26 um 10 42 13

**Comment by bierik** [comment]
I see i need this changes to reproduce that issue https://github.com/4teamwork/ftw.mobilenavigation/issues/32.

Please make a PR for https://github.com/4teamwork/ftw.mobilenavigation/issues/32.

Looks good with both changes thanks a lot :+1: .

**Comment by djowett** [comment]
Agreed it's this fix for #32 that makes this happen.

     .globalnav li a {
        margin-right: 0;
     }

Adding .current to the rule above would fix #32 without this PR I guess, but I float right seems tidier (IMO) anyway.  What do you prefer?

**Comment by djowett** [comment]
PR for #32 is done.

**Comment by bierik** [comment]
Thank you looks good :+1:.. i would prefer the tidier way too

**Comment by djowett** [comment]
Great, thanks. Do you have plans to do a release this week by any chance?

**Comment by maethu** [comment]
Hey @djowett I just released Version 1.4.3 on pypi (incl. your improvements).
Thanks for your contribution! :sparkling_heart:

**Comment by djowett** [comment]
@maethu Thanks - it's looking good :-)

**Pull request merged**
